language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - pip install coveralls
# test command
script: py.test --cov fs
after_success: coveralls
branches:
  only:
    - master